name: First CICD pipleline

on:
  push:
    branches: ["main"]

jobs:
  clone-repo-in-VPS:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the server 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          script: |
            git clone git@github.com:Faiz-js/CICD-pipeline-using-github-actions.git