name: First CICD pipleline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the server 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          script: |
            cd ~/CICD-pipeline-using-github-actions

            git pull origin main

            docker stop gh-actions-container || true

            docker rm gh-actions-container || true

            docker rmi gh-actions-image || true

            docker build -t gh-actions-image .

            docker run -d -p 3000:80 --name gh-actions-container gh-actions-image