name: First CICD pipleline

on:
  push:
    branches: ["main"]

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: echo step1
        run: echo "THE PIPELINE IS WORKING FINE"

    steps:
      - name: echo step2
        run: echo "THE PIPELINE ECHO"

